coder:
  env:
    - name: CODER_ACCESS_URL
      value: "" 
  ingress:
    enabled: true
    className: "traefik"
    wildcardHost: ""
    tls:
      enable: true
      secretName: "coder-cert" 
      wildcardSecretName: "coder-wildcard-cert"