coder:
  env:
    - name: CODER_ACCESS_URL
      value: "" 
  ingress:
    enable: true
    className: "traefik"
    host: ""
    wildcardHost: ""
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      acme.cert-manager.io/http01-ingress-class: "traefik" 
    tls:
      enable: true
      secretName: "coder-cert" 
      wildcardSecretName: "coder-wildcard-cert"